# Generated by Django 5.1.4 on 2026-01-03 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_note_category_note_color_note_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quadrant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quadrants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuadrantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadrant', models.CharField(choices=[('urgent_important', 'Urgent & Important'), ('not_urgent_important', 'Important, Not Urgent'), ('urgent_not_important', 'Urgent, Not Important'), ('not_urgent_not_important', 'Neither Urgent nor Important')], default='urgent_important', max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadrant_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
